ALTER TABLE `loan_repayments` ADD `month` int;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `year` int;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `status` enum('pending','approved','paid','withheld') DEFAULT 'pending';--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `withheldAt` timestamp;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `withheldReason` text;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `chequeNumber` varchar(50);--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `chequeImageUrl` text;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `invoiceUrl` text;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `authorisedById` int;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `authorisedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `authorisedAt` timestamp;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `rejectedById` int;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `rejectedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `rejectedAt` timestamp;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `rejectionComment` text;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `deferredToMonth` int;--> statement-breakpoint
ALTER TABLE `loan_repayments` ADD `deferredToYear` int;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `authorisedById` int;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `authorisedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `authorisedAt` timestamp;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `rejectedById` int;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `rejectedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `rejectedAt` timestamp;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `rejectionComment` text;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `deferredToMonth` int;--> statement-breakpoint
ALTER TABLE `payroll_records` ADD `deferredToYear` int;--> statement-breakpoint
ALTER TABLE `receipts` ADD `authorisedById` int;--> statement-breakpoint
ALTER TABLE `receipts` ADD `authorisedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `receipts` ADD `authorisedAt` timestamp;--> statement-breakpoint
ALTER TABLE `receipts` ADD `rejectedById` int;--> statement-breakpoint
ALTER TABLE `receipts` ADD `rejectedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `receipts` ADD `rejectedAt` timestamp;--> statement-breakpoint
ALTER TABLE `receipts` ADD `rejectionComment` text;--> statement-breakpoint
ALTER TABLE `receipts` ADD `deferredToMonth` int;--> statement-breakpoint
ALTER TABLE `receipts` ADD `deferredToYear` int;--> statement-breakpoint
ALTER TABLE `receipts` ADD `paymentStatus` enum('pending','paid','withheld') DEFAULT 'pending';--> statement-breakpoint
ALTER TABLE `receipts` ADD `withheldAt` timestamp;--> statement-breakpoint
ALTER TABLE `receipts` ADD `withheldReason` text;--> statement-breakpoint
ALTER TABLE `receipts` ADD `chequeAmount` decimal(10,2);--> statement-breakpoint
ALTER TABLE `receipts` ADD `totalAmount` decimal(10,2);--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `authorisedById` int;--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `authorisedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `authorisedAt` timestamp;--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `rejectedById` int;--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `rejectedByName` varchar(200);--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `rejectedAt` timestamp;--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `rejectionComment` text;--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `deferredToMonth` int;--> statement-breakpoint
ALTER TABLE `volunteer_payments` ADD `deferredToYear` int;