CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`month` int NOT NULL,
	`year` int NOT NULL,
	`category` varchar(100) NOT NULL,
	`subCategory` varchar(100),
	`vendor` varchar(200),
	`description` text,
	`invoiceNumber` varchar(100),
	`invoiceDate` date,
	`amount` decimal(12,2) NOT NULL,
	`paymentMethod` enum('cheque','bank_transfer','cash') DEFAULT 'cheque',
	`paymentStatus` enum('pending','paid','withheld') NOT NULL DEFAULT 'pending',
	`paidAt` timestamp,
	`withheldAt` timestamp,
	`withheldReason` text,
	`chequeNumber` varchar(50),
	`chequeDate` date,
	`chequeAmount` decimal(12,2),
	`chequeImageUrl` text,
	`evidenceUrl` text,
	`authorisedById` int,
	`authorisedByName` varchar(200),
	`authorisedAt` timestamp,
	`rejectedById` int,
	`rejectedByName` varchar(200),
	`rejectedAt` timestamp,
	`rejectionComment` text,
	`deferredToMonth` int,
	`deferredToYear` int,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
