CREATE TABLE `accommodation_rent_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`periodLabel` varchar(100) NOT NULL,
	`periodStart` date NOT NULL,
	`periodEnd` date NOT NULL,
	`dueDate` date NOT NULL,
	`amountDue` decimal(10,2) NOT NULL,
	`amountPaid` decimal(10,2),
	`status` enum('pending','paid','partial','overdue','waived') NOT NULL DEFAULT 'pending',
	`paidDate` date,
	`paymentMethod` enum('bank_transfer','cash','cheque','standing_order','other'),
	`receiptUrl` text,
	`confirmedByUserId` int,
	`confirmedByName` varchar(200),
	`confirmedAt` timestamp,
	`reminderSentAt` timestamp,
	`overdueSentAt` timestamp,
	`escalationSentAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accommodation_rent_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `accommodation_tenants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(200) NOT NULL,
	`email` varchar(320),
	`phone` varchar(30),
	`whatsappPhone` varchar(30),
	`roomNumber` varchar(50),
	`propertyAddress` text,
	`contractStartDate` date,
	`contractEndDate` date,
	`contractDocUrl` text,
	`rentAmount` decimal(10,2) NOT NULL,
	`rentFrequency` enum('weekly','monthly','quarterly') NOT NULL DEFAULT 'monthly',
	`rentDueDay` int NOT NULL DEFAULT 1,
	`depositAmount` decimal(10,2),
	`depositPaidDate` date,
	`depositRefundedDate` date,
	`depositNotes` text,
	`status` enum('active','inactive','notice_given','vacated') NOT NULL DEFAULT 'active',
	`emergencyContactName` varchar(200),
	`emergencyContactPhone` varchar(30),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accommodation_tenants_id` PRIMARY KEY(`id`)
);
