CREATE TABLE `payroll_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`month` int NOT NULL,
	`year` int NOT NULL,
	`status` enum('draft','submitted','approved','finalised','rejected') NOT NULL DEFAULT 'draft',
	`submittedById` int,
	`submittedByName` varchar(200),
	`submittedAt` timestamp,
	`approver1Id` int,
	`approver1Name` varchar(200),
	`approver1At` timestamp,
	`approver1Comment` text,
	`approver2Id` int,
	`approver2Name` varchar(200),
	`approver2At` timestamp,
	`approver2Comment` text,
	`rejectedById` int,
	`rejectedByName` varchar(200),
	`rejectedAt` timestamp,
	`rejectionComment` text,
	`fpsXmlUrl` text,
	`fpsExportedAt` timestamp,
	`fpsExportedById` int,
	`totalGross` decimal(12,2) DEFAULT '0',
	`totalTax` decimal(12,2) DEFAULT '0',
	`totalNI` decimal(12,2) DEFAULT '0',
	`totalPension` decimal(12,2) DEFAULT '0',
	`totalNet` decimal(12,2) DEFAULT '0',
	`employeeCount` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pension_enrolments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL DEFAULT 0,
	`employeeName` varchar(200) NOT NULL,
	`niNumber` varchar(20),
	`status` enum('not_eligible','eligible_not_enrolled','enrolled','opted_out','postponed') NOT NULL DEFAULT 'not_eligible',
	`monthlyQualifyingEarnings` decimal(10,2) DEFAULT '0',
	`employeeContributionPct` decimal(5,2) DEFAULT '5.00',
	`employerContributionPct` decimal(5,2) DEFAULT '3.00',
	`assessmentDate` date,
	`enrolmentDate` date,
	`optOutDate` date,
	`postponementEndDate` date,
	`pensionProvider` varchar(200),
	`pensionSchemeRef` varchar(100),
	`approachingThreshold` boolean DEFAULT false,
	`notifiedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pension_enrolments_id` PRIMARY KEY(`id`)
);
