CREATE TABLE `enquiry_audit_trail` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enquiryId` int NOT NULL,
	`action` varchar(200) NOT NULL,
	`description` text,
	`performedByUserId` int,
	`performedByName` varchar(200),
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`metadata` json,
	CONSTRAINT `enquiry_audit_trail_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `enquiry_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enquiryId` int NOT NULL,
	`paymentType` enum('deposit','fifty_percent','full_payment','other') NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`dueDate` date,
	`status` enum('pending','received','overdue') NOT NULL DEFAULT 'pending',
	`paidAt` timestamp,
	`authorisedByUserId` int,
	`authorisedByName` varchar(200),
	`authorisedAt` timestamp,
	`evidenceUrl` text,
	`evidenceNotes` text,
	`paymentMethod` enum('cash','bank_transfer','card','cheque'),
	`reference` varchar(200),
	`confirmationSentAt` timestamp,
	`confirmationMethod` enum('email','whatsapp','both'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `enquiry_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `facility_enquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stage` enum('general_enquiry','interested','going_ahead','confirmed','cancelled') NOT NULL DEFAULT 'general_enquiry',
	`eventType` enum('wedding','conference','community_event','funeral','birthday','corporate','charity','religious','other') NOT NULL DEFAULT 'other',
	`eventTypeOther` varchar(200),
	`eventDate` date,
	`eventStartTime` varchar(10),
	`eventEndTime` varchar(10),
	`expectedAttendees` int,
	`contactName` varchar(200) NOT NULL,
	`contactEmail` varchar(320),
	`contactPhone` varchar(30),
	`contactAddress` text,
	`isOrganisation` boolean NOT NULL DEFAULT false,
	`organisationName` varchar(200),
	`organisationAddress` text,
	`leadContactName` varchar(200),
	`leadContactRole` varchar(100),
	`roomId` int,
	`roomPreference` varchar(200),
	`foodRequired` boolean NOT NULL DEFAULT false,
	`foodHeadcount` int,
	`cateringType` enum('internal','external','self_catering','none') DEFAULT 'none',
	`teaCoffeeRequired` boolean NOT NULL DEFAULT false,
	`tablesRequired` boolean NOT NULL DEFAULT false,
	`tablesCount` int,
	`chairsRequired` boolean NOT NULL DEFAULT false,
	`chairsCount` int,
	`cutleryPlatesRequired` boolean NOT NULL DEFAULT false,
	`cutleryPlatesCount` int,
	`decorRequired` boolean NOT NULL DEFAULT false,
	`decorType` enum('internal','external','both','none') DEFAULT 'none',
	`decorNotes` text,
	`speakersRequired` boolean NOT NULL DEFAULT false,
	`micSystemRequired` boolean NOT NULL DEFAULT false,
	`avNotes` text,
	`meetAndGreetRoom` boolean NOT NULL DEFAULT false,
	`groomRoom` boolean NOT NULL DEFAULT false,
	`brideRoom` boolean NOT NULL DEFAULT false,
	`additionalRoomNotes` text,
	`parkingRequired` boolean NOT NULL DEFAULT false,
	`parkingSpaces` int,
	`beveragesRequired` boolean NOT NULL DEFAULT false,
	`beveragesNotes` text,
	`agreedAmount` decimal(10,2),
	`depositAmount` decimal(10,2),
	`formSentAt` timestamp,
	`formSentBy` int,
	`formReturnedAt` timestamp,
	`bookingId` int,
	`notes` text,
	`sourceDocument` text,
	`createdByUserId` int,
	`assignedToUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `facility_enquiries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_briefing_prefs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`enabled` boolean NOT NULL DEFAULT true,
	`includeLoans` boolean NOT NULL DEFAULT true,
	`includeDonations` boolean NOT NULL DEFAULT true,
	`includePayroll` boolean NOT NULL DEFAULT true,
	`includePledges` boolean NOT NULL DEFAULT true,
	`includeTenants` boolean NOT NULL DEFAULT true,
	`includeCompliance` boolean NOT NULL DEFAULT true,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_briefing_prefs_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_briefing_prefs_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `voice_quick_actions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`pageKey` varchar(100) NOT NULL,
	`actions` text NOT NULL DEFAULT ('[]'),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `voice_quick_actions_id` PRIMARY KEY(`id`)
);
